apiVersion: batch/v1
kind: Job
metadata:
  name: sqlite-restore
  namespace: pra
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: alpine
          command: ["/bin/sh","-c"]
          args:
            - |
              if [ -n "$RESTORE_FILE" ] && [ -f "/backup/$RESTORE_FILE" ]; then
                TARGET="/backup/$RESTORE_FILE"
              else
                TARGET=$(ls -t /backup/*.db 2>/dev/null | head -1)
              fi

              if [ -z "$TARGET" ]; then
                echo "No backup file found in /backup" >&2
                exit 1
              fi

              cp "$TARGET" /data/app.db
          env:
            - name: RESTORE_FILE
              value: ""
          volumeMounts:
            - name: data
              mountPath: /data
            - name: backup
              mountPath: /backup
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pra-data
        - name: backup
          persistentVolumeClaim:
            claimName: pra-backup
